### ISSUE TITLE
Full Integer Deployment

### ISSUE THREAD

**Issue by dtlam26** [sayakpaul/Adventures-in-TensorFlow-Lite#1]
Sorry, but I have taken a look at your example. It is good to see some complete examples like this. However, the title somehow sometimes seems misleading when the 8bit integer model is not actually 8 bit. When you let the optimizer default, it means some layers will not be quantized.

**Comment by sayakpaul** [comment]
Probably that won't be the case when we enforce the inference input and output types as [this guide](https://www.tensorflow.org/lite/performance/post_training_integer_quant). 

Cc: @khanhlvg
