### ISSUE TITLE
No model size reduction in Tflite model size with integer Quantisation 

### ISSUE THREAD

**Issue by letdivedeep** [sayakpaul/Adventures-in-TensorFlow-Lite#3]
Hi @sayakpaul 

Thanks for the detailed conversion examples.

I have trained a PyTorch model, which I converted to Keras using the pytorch2keras lib. 

using this Keras model to convert to tflite.  I want to run the tflite on coral devices. 

things which i noticed :
- Keras model size (57.6MB)
- Using dynamic range quantization the generated tflite is of size(15MB)
- Using integer only quantization the  generated tflite is also of size(15MB)

Ideally, we should be able to reduce the model size even further as we convert fp32 to int8

Could you point me out, if i am missing anything here? 

shared my conversion notebook and Keras modelkeras_model

[data](https://drive.google.com/file/d/1rU3Ox1RPl-IV3Ul4DV8hq8AnveYhFCUT/view?usp=sharing)

**Comment by sayakpaul** [comment]
Sorry, I don't have the bandwidth to look into other models right now. I would suggest posting your queries to TensorFlow Discuss Forum: discuss.tensorflow.org.

**Comment by letdivedeep** [comment]
> Sorry, I don't have the bandwidth to look into other models right now. I would suggest posting your queries to TensorFlow Discuss Forum: discuss.tensorflow.org.

No Issues @sayakpaul .. will post it on the tf forum
