### ISSUE TITLE
Can not convert to TFLite

### ISSUE THREAD

**Issue by tuandoan998** [sayakpaul/Adventures-in-TensorFlow-Lite#4]
Hi Mr. @sayakpaul 
Thank you for the example convert to TFLite model.
I have successfully converted the pretrained models of DeepLabv3 to TFLite model. I have this suggestion, if you use _**output_arrays=['ArgMax']**_ instead of _**['ResizeBilinear_2']**_ the output_shape of the TFLite model is 513 instead of 65.

I ran the [local_test.sh](https://github.com/tensorflow/models/blob/master/research/deeplab/local_test.sh) file from the original repo, and frozen_inference_graph.pb cannot be converted to TFLite by your method (The frozen_inference_graph.pb file has run successfully with deeplab_demo.ipynb). When converting to TFLite, an error occurs: "ValueError: Invalid tensors 'sub_7' were found."

Do you have any advice? Thank you.

**Comment by sayakpaul** [comment]
This is why the argmax part is not included during conversion. We do it separately after performing inference with the converted TFLite model. 

As far as I know argmax op is not that optimized for the GPU delegate as well. So, that's a good reason to exclude it. 

Cc: @khanhlvg

**Comment by tuandoan998** [comment]
I tried replacing ArgMax by ResizeBilinear_2, but it keeps giving me the error.
Error occurred in **input_arrays = ['sub_7']**.

**Comment by sayakpaul** [comment]
That is weird. Not sure what's going wrong in there. 

@khanhlvg could you help?

**Comment by tuandoan998** [comment]
I solved the problem.
Tensor 'sub_7' does not exist in the graph after retraining. I used **input_arrays = ['MobilenetV2/MobilenetV2/input']** and it was successful.
Thank you

**Comment by sayakpaul** [comment]
I see. Glad you were able to do that! 

If you want to submit a PR demoing this particular use case please go right ahead.
