### ISSUE TITLE
different color for each instance

### ISSUE THREAD

**Issue by Bill4869** [sayakpaul/Adventures-in-TensorFlow-Lite#7]
Hello.
Thank you for your great deeplap usage notebooks.
I would like to know if there is anyway I can color each instance separately?

Thank you in advances.
Bill

**Comment by sayakpaul** [comment]
Could you provide an example of what you're looking for?

**Comment by Bill4869** [comment]
By using your deeplab notebook, objects with the same class will have the same color but I want every single object to have different color, same as instance segmentation. (in the below image, i want the result on the right one)
![image](https://user-images.githubusercontent.com/31407241/173760767-3f47ccf0-007f-40d0-a82d-9b80f615bde1.png)
Is there a way to implement that using your notebook?

**Comment by sayakpaul** [comment]
For that, the model needs to be an instance segmentation model in the first place. The DeepLabV3 model is probably not that.
