### ISSUE TITLE
quantization_strategy=="int8" does not quantize the model

### ISSUE THREAD

**Issue by alexander-sony** [sayakpaul/Adventures-in-TensorFlow-Lite#8]
Hi Paul!

Have a question for **MobileDet_Conversion_TFLite.ipynb**, Quantize and serialize.

Using model: ```model_checkpoint_name = "ssd_mobiledet_cpu_coco"```

Is my understanding correct: using 
```original_precision = "regular"```
```quantization_strategy = "int8"```

We expect that the converted model is a quantized model, with input as uint8 (```converter.inference_input_type = tf.uint8```).
However, the resulting model input is not quantized:
```input_type = interpreter.get_input_details()[0]['dtype']```
```print('input_type: ' + str(input_type))```
```input_type: <class 'numpy.float32'>```

Moreover, checking the resulting tflite file using netron.app shows that the model is missing the Quantize step after normalized_input_image_tensor.

Is ```quantization_strategy=="int8"``` missing ```converter.representative_dataset = representative_dataset_gen```?

**Comment by sayakpaul** [comment]
Thanks for reporting!

Since the pure CPU model doesn't benefit much from the full integer quantization, it wasn't utilized further. More details are in this post: https://sayak.dev/mobiledet-optimization/
